# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msgs.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmsgs.proto\"p\n\x0f\x43ontrollerState\x12\x17\n\x0fleft_joystick_x\x18\x01 \x01(\x02\x12\x17\n\x0fleft_joystick_y\x18\x02 \x01(\x02\x12\x14\n\x0cleft_trigger\x18\x03 \x01(\x02\x12\x15\n\rright_trigger\x18\x04 \x01(\x02\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"[\n\tGameState\x12\"\n\x10\x63\x61mera_direction\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x1a\n\x08velocity\x18\x02 \x01(\x0b\x32\x08.Vector3\x12\x0e\n\x06\x64\x61mage\x18\x03 \x01(\x07\x42\x0b\xaa\x02\x08Messages')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\010Messages'
  _globals['_CONTROLLERSTATE']._serialized_start=14
  _globals['_CONTROLLERSTATE']._serialized_end=126
  _globals['_VECTOR3']._serialized_start=128
  _globals['_VECTOR3']._serialized_end=170
  _globals['_GAMESTATE']._serialized_start=172
  _globals['_GAMESTATE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
